<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Twilio\Rest\Client;
use App\Models\Admin;
use App\Models\User;
use App\Models\Permission;
use App\Models\Role;
use Illuminate\Support\Facades\Validator;
use Carbon\Carbon;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;

class PermissionApiController extends Controller
{
    public function assignPermissionToRole(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'role_id'   => 'required|integer|exists:roles,id|unique:permissions,role_id,',
            'dashboard' => 'nullable|boolean',
            'admins' => 'nullable|boolean',
            'subadmin' => 'nullable|boolean',
            'users' => 'nullable|boolean',
            'drivers' => 'nullable|boolean',
            'manager' => 'nullable|boolean',
            'accountant' => 'nullable|boolean',
            'marketing' => 'nullable|boolean',
            'b_dashboard' => 'nullable|boolean',
            'sharing_new_booking' => 'nullable|boolean',
            'sharing_confirm' => 'nullable|boolean',
            'sharing_assign' => 'nullable|boolean',
            'sharing_accept' => 'nullable|boolean',
            'sharing_en_route' => 'nullable|boolean',
            'sharing_complete' => 'nullable|boolean',
            'sharing_cancel' => 'nullable|boolean',
            'private_new_booking' => 'nullable|boolean',
            'private_confirm' => 'nullable|boolean',
            'private_assign' => 'nullable|boolean',
            'private_accept' => 'nullable|boolean',
            'private_en_route' => 'nullable|boolean',
            'private_complete' => 'nullable|boolean',
            'private_cancel' => 'nullable|boolean',
            'toairport_new_booking' => 'nullable|boolean',
            'toairport_confirm' => 'nullable|boolean',
            'toairport_assign' => 'nullable|boolean',
            'toairport_accept' => 'nullable|boolean',
            'toairport_en_route' => 'nullable|boolean',
            'toairport_complete' => 'nullable|boolean',
            'toairport_cancel' => 'nullable|boolean',
            'fromairport_new_booking' => 'nullable|boolean',
            'fromairport_confirm' => 'nullable|boolean',
            'fromairport_assign' => 'nullable|boolean',
            'fromairport_accept' => 'nullable|boolean',
            'fromairport_en_route' => 'nullable|boolean',
            'fromairport_complete' => 'nullable|boolean',
            'fromairport_cancel' => 'nullable|boolean',
            'drivetest_new_booking' => 'nullable|boolean',
            'drivetest_confirm' => 'nullable|boolean',
            'drivetest_assign' => 'nullable|boolean',
            'drivetest_accept' => 'nullable|boolean',
            'drivetest_en_route' => 'nullable|boolean',
            'drivetest_complete' => 'nullable|boolean',
            'drivetest_cancel' => 'nullable|boolean',
            'intercity_new_booking' => 'nullable|boolean',
            'intercity_confirm' => 'nullable|boolean',
            'intercity_assign' => 'nullable|boolean',
            'intercity_accept' => 'nullable|boolean',
            'intercity_en_route' => 'nullable|boolean',
            'intercity_complete' => 'nullable|boolean',
            'intercity_cancel' => 'nullable|boolean',
            'ab_new_booking' => 'nullable|boolean',
            'ab_confirm' => 'nullable|boolean',
            'ab_cancel' => 'nullable|boolean',
            'route_new_booking' => 'nullable|boolean',
            'route_confirm' => 'nullable|boolean',
            'route_cancel' => 'nullable|boolean',
            'out_of_area' => 'nullable|boolean',
            'cs_dashboard' => 'nullable|boolean',
            'chat_support' => 'nullable|boolean',
            'fm_dashboard' => 'nullable|boolean',
            'deposits' => 'nullable|boolean',
            'd_withdraw' => 'nullable|boolean',
            'switch' => 'nullable|boolean',
            'ac_dashboard' => 'nullable|boolean',
            'ads_user' => 'nullable|boolean',
            'ads_on_route' => 'nullable|boolean',
            'ads_end_receipt' => 'nullable|boolean',
            'ads_driver' => 'nullable|boolean',
            'notify' => 'nullable|boolean',
            'deals_user' => 'nullable|boolean',
            'deals_driver' => 'nullable|boolean',
            'website' => 'nullable|boolean',
            'pc_dashboard' => 'nullable|boolean',
            'categeries' => 'nullable|boolean',
            'cities' => 'nullable|boolean',
            'add_sharing' => 'nullable|boolean',
            'add_private' => 'nullable|boolean',
            'add_to_airport' => 'nullable|boolean',
            'add_from_airport' => 'nullable|boolean',
            'add_drive' => 'nullable|boolean',
            'add_intercity' => 'nullable|boolean',
            'rates' => 'nullable|boolean',
            'surge' => 'nullable|boolean',
            'commission' => 'nullable|boolean',
            'gt_charges' => 'nullable|boolean',
            'interac_id' => 'nullable|boolean',
            'payout_info' => 'nullable|boolean',
            'pc_cancel' => 'nullable|boolean',
            'r_dashboard' => 'nullable|boolean',
            'report' => 'nullable|boolean',
            's_dashboard' => 'nullable|boolean',
            'faq_user' => 'nullable|boolean',
            'faq_driver' => 'nullable|boolean',
            'tc_user' => 'nullable|boolean',
            'tc_driver' => 'nullable|boolean',
            'pp_user' => 'nullable|boolean',
            'pp_driver' => 'nullable|boolean',
            'support' => 'nullable|boolean',
            'date' => 'nullable|date',
            'time' => 'nullable|date_format:H:i:s',
            'is_read' => 'nullable|boolean',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'message' => 'Validation Fail',
                'status' => 'failure',
                'statusCode' => '400',
                'data' => $validator->errors(),
            ], 400);
        }

        $permission = Permission::create([
            'role_id' => $request->role_id,
            'dashboard' => $request->dashboard ?? 0,
            'admins' => $request->admins ?? 0,
            'subadmin' => $request->subadmin ?? 0,
            'users' => $request->users ?? 0,
            'drivers' => $request->drivers ?? 0,
            'manager' => $request->manager ?? 0,
            'accountant' => $request->accountant ?? 0,
            'marketing' => $request->marketing ?? 0,
            'b_dashboard' => $request->b_dashboard ?? 0,
            'sharing_new_booking' => $request->sharing_new_booking ?? 0,
            'sharing_confirm' => $request->sharing_confirm ?? 0,
            'sharing_assign' => $request->sharing_assign ?? 0,
            'sharing_accept' => $request->sharing_accept ?? 0,
            'sharing_en_route' => $request->sharing_en_route ?? 0,
            'sharing_complete' => $request->sharing_complete ?? 0,
            'sharing_cancel' => $request->sharing_cancel ?? 0,
            'private_new_booking' => $request->private_new_booking ?? 0,
            'private_confirm' => $request->private_confirm ?? 0,
            'private_assign' => $request->private_assign ?? 0,
            'private_accept' => $request->private_accept ?? 0,
            'private_en_route' => $request->private_en_route ?? 0,
            'private_complete' => $request->private_complete ?? 0,
            'private_cancel' => $request->private_cancel ?? 0,
            'toairport_new_booking' => $request->toairport_new_booking ?? 0,
            'toairport_confirm' => $request->toairport_confirm ?? 0,
            'toairport_assign' => $request->toairport_assign ?? 0,
            'toairport_accept' => $request->toairport_accept ?? 0,
            'toairport_en_route' => $request->toairport_en_route ?? 0,
            'toairport_complete' => $request->toairport_complete ?? 0,
            'toairport_cancel' => $request->toairport_cancel ?? 0,
            'fromairport_new_booking' => $request->fromairport_new_booking ?? 0,
            'fromairport_confirm' => $request->fromairport_confirm ?? 0,
            'fromairport_assign' => $request->fromairport_assign ?? 0,
            'fromairport_accept' => $request->fromairport_accept ?? 0,
            'fromairport_en_route' => $request->fromairport_en_route ?? 0,
            'fromairport_complete' => $request->fromairport_complete ?? 0,
            'fromairport_cancel' => $request->fromairport_cancel ?? 0,
            'drivetest_new_booking' => $request->drivetest_new_booking ?? 0,
            'drivetest_confirm' => $request->drivetest_confirm ?? 0,
            'drivetest_assign' => $request->drivetest_assign ?? 0,
            'drivetest_accept' => $request->drivetest_accept ?? 0,
            'drivetest_en_route' => $request->drivetest_en_route ?? 0,
            'drivetest_complete' => $request->drivetest_complete ?? 0,
            'drivetest_cancel' => $request->drivetest_cancel ?? 0,
            'intercity_new_booking' => $request->intercity_new_booking ?? 0,
            'intercity_confirm' => $request->intercity_confirm ?? 0,
            'intercity_assign' => $request->intercity_assign ?? 0,
            'intercity_accept' => $request->intercity_accept ?? 0,
            'intercity_en_route' => $request->intercity_en_route ?? 0,
            'intercity_complete' => $request->intercity_complete ?? 0,
            'intercity_cancel' => $request->intercity_cancel ?? 0,
            'ab_new_booking' => $request->ab_new_booking ?? 0,
            'ab_confirm' => $request->ab_confirm ?? 0,
            'ab_cancel' => $request->ab_cancel ?? 0,
            'route_new_booking' => $request->route_new_booking ?? 0,
            'route_confirm' => $request->route_confirm ?? 0,
            'route_cancel' => $request->route_cancel ?? 0,
            'out_of_area' => $request->out_of_area ?? 0,
            'cs_dashboard' => $request->cs_dashboard ?? 0,
            'chat_support' => $request->chat_support ?? 0,
            'fm_dashboard' => $request->fm_dashboard ?? 0,
            'deposits' => $request->deposits ?? 0,
            'd_withdraw' => $request->d_withdraw ?? 0,
            'switch' => $request->switch ?? 0,
            'ac_dashboard' => $request->ac_dashboard ?? 0,
            'ads_user' => $request->ads_user ?? 0,
            'ads_on_route' => $request->ads_on_route ?? 0,
            'ads_end_receipt' => $request->ads_end_receipt ?? 0,
            'ads_driver' => $request->ads_driver ?? 0,
            'notify' => $request->notify ?? 0,
            'deals_user' => $request->deals_user ?? 0,
            'deals_driver' => $request->deals_driver ?? 0,
            'website' => $request->website ?? 0,
            'pc_dashboard' => $request->pc_dashboard ?? 0,
            'categeries' => $request->categeries ?? 0,
            'cities' => $request->cities ?? 0,
            'add_sharing' => $request->add_sharing ?? 0,
            'add_private' => $request->add_private ?? 0,
            'add_to_airport' => $request->add_to_airport ?? 0,
            'add_from_airport' => $request->add_from_airport ?? 0,
            'add_drive' => $request->add_drive ?? 0,
            'add_intercity' => $request->add_intercity ?? 0,
            'rates' => $request->rates ?? 0,
            'surge' => $request->surge ?? 0,
            'commission' => $request->commission ?? 0,
            'gt_charges' => $request->gt_charges ?? 0,
            'interac_id' => $request->interac_id ?? 0,
            'payout_info' => $request->payout_info ?? 0,
            'pc_cancel' => $request->pc_cancel ?? 0,
            'r_dashboard' => $request->r_dashboard ?? 0,
            'report' => $request->report ?? 0,
            's_dashboard' => $request->s_dashboard ?? 0,
            'faq_user' => $request->faq_user ?? 0,
            'faq_driver' => $request->faq_driver ?? 0,
            'tc_user' => $request->tc_user ?? 0,
            'tc_driver' => $request->tc_driver ?? 0,
            'pp_user' => $request->pp_user ?? 0,
            'pp_driver' => $request->pp_driver ?? 0,
            'support' => $request->support ?? 0,
            'date' => now(),
            'time' => now(),
            'is_read' => 0,
        ]);

        return response()->json([
            'message' => 'Permission created successfully',
            'status' => 'success',
            'statusCode' => '200',
            'data' => $permission
        ], 201);
    }

}
